import type { Metadata } from 'next'
import './mdx.css'
import { PADDING_TOP } from '@/app/const'
import { cn } from '../../../../lib/utils'
import { TableOfContents } from '@/components/TableOfContents'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="relative mx-auto max-w-7xl">
      <TableOfContents />
      <article className={cn('prose mx-auto max-w-3xl px-4', PADDING_TOP)}>{children}</article>
    </div>
  )
}
