import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="bg-[rgba(28,28,30)]" suppressHydrationWarning>
      <body suppressHydrationWarning className="">
        <Header />
        {children}
      </body>
    </html>
  )
}
